version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: simple-https-frontend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simple-https-backend
    restart: unless-stopped
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    container_name: simple-https-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge